# modern tmux yay
set -g default-terminal "xterm-256color"
set -a terminal-features "xterm-256color"
set -ga terminal-overrides ",alacritty:RGB"
set -as terminal-overrides ',xterm-256color:cursor_shape=0'
set -g default-shell /bin/zsh
set -g mouse on
set -g set-clipboard on

# misc config options
# mostly from tmux-sensible

set -g prefix C-a

set -g escape-time 0
set -g history-limit 100000
set -g status-interval 5
set -g focus-events on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g aggressive-resize on

set -g automatic-rename on
set -wg automatic-rename on

# keybindings

bind-key d detach
bind-key v server-info
bind-key ? list-keys
bind-key A command-prompt 'rename-window %%'
bind-key C-a last-window
bind : command-prompt
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

unbind-key x
bind-key x kill-pane
bind-key X kill-session

source-file ~/.tmux.theme
# alternative color scheme: https://github.com/ivnvxd/tmux-snazzy

#--- TPM
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @resurrect-strategy-nvim 'session'
# needs nvim sessions: https://github.com/tpope/vim-obsession

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'
# set -g @continuum-boot-options 'ghostty'
# needs https://github.com/tmux-plugins/tmux-continuum/pull/146

# set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'joshmedeski/tmux-fzf-url'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g status-right '#{prefix_highlight} '

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

